#image: gitpod/workspace-mongodb

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/

tasks:
  - init: |
      npm install
      npm run build
      gp sync-done packages
    command: |
      npm run start
  - init: gp sync-await packages
    command: |
      npm run hardhat:chain
    name: Hardhat

vscode:
  extensions:
    - dbaeumer.vscode-eslint
